version: '3'

services:
  chad:
    image: $DOCKER_REGISTRY/chad/server
    environment:
      - REDIS_URL=redis://cache/1
      - CLEANUP_DISABLED=yes
      - DOCKER_REGISTRY=$DOCKER_REGISTRY
      - GATEWAY_IMAGE=$DOCKER_REGISTRY/chad/gateway
    volumes:
      - .data/chad_pki:/etc/chad_pki
      - /var/run/docker.sock:/run/docker.sock
    depends_on:
      - cache
    networks:
      - internal

  app:
    build: .
    image: $DOCKER_REGISTRY/ctfd
    ports:
      - "8000:8000"
    environment:
      - DEBUG=yes
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://root:ctfd@db/ctfd
      - REDIS_URL=redis://cache/0
      - ACCESS_LOG=-
      - ERROR_LOG=-
    volumes:
      - .data/logs:/var/log/CTFd
      - .data/uploads:/var/lib/CTFd/uploads
      - .:/opt/CTFd:ro
    depends_on:
      - db
      - cache
    networks:
      - default
      - internal

  db:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      - internal
    # This command is required to set important mariadb defaults
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --wait_timeout=28800
      - --log-warnings=0

  cache:
    image: redis:alpine
    volumes:
      - .data/redis:/data
    networks:
      internal:

networks:
  default:
  internal:
    internal: true
