version: '3'

services:
  app:
    build: .
    image: ${REGISTRY}/ctfd
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+mysqldb://root:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
    volumes:
      - .data/CTFd/logs:/var/log/CTFd
      - .data/CTFd/uploads:/var/lib/uploads
      - .:/opt/CTFd:ro
    depends_on:
      - db
    networks:
      - default
      - internal

  db:
    image: mariadb:10
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      - internal
    # This command is required to set important mariadb defaults
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --wait_timeout=28800

  cache:
    image: redis:alpine
    restart: on-failure
    volumes:
    - .data/redis:/data
    networks:
      - internal

networks:
  default:
  internal:
    internal: true
